name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 liblua5.4-dev luarocks

      - name: Install Dependencies from rockspec
        run: luarocks make --local

      - name: Add local bin to PATH
        run: echo "::add-path::$HOME/.luarocks/bin"

      - name: Run Tests
        run: busted spec
