name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'


      - name: Install dependencies
        run: luarocks install --local
    
      - name: Build
        run: luarocks make --local

      - name: Run Tests
        run: busted spec
